spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #避免将驼峰命名转换为下划线命名
  mail:
    host: smtp.163.com
    username: kkvv_110@163.com
    password: LDEKSPRYUXIRXVNT

#自定义参数，防爆刷（限制单个客户端IP在最近X分钟内请求注册接口不能超过Y次）
customize:
  intervalSecond: 30
  limitRequests: 3
